# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
one_dim = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a 2-dimensional NumPy array using np.array()
two_dim = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
three_dim = np.array([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]],
                      [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_dim.ndim, type(one_dim), one_dim.size, one_dim.dtype

(1, numpy.ndarray, 10, dtype('int64'))

In [4]:
# Attributes of 2-dimensional array
two_dim.ndim, type(two_dim), two_dim.size, two_dim.dtype

(2, numpy.ndarray, 9, dtype('int64'))

In [5]:
# Attributes of 3-dimensional array
three_dim.ndim, type(three_dim), three_dim.size, three_dim.dtype

(3, numpy.ndarray, 18, dtype('int64'))

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

three_dim_df = pd.DataFrame(two_dim)
three_dim_df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
# Create an array of shape (10, 2) with only ones
arr = np.ones((10, 2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
arr = np.zeros((7, 2, 3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr = np.random.randint(0, 10, size=(7, 2))
arr

array([[3, 5],
       [5, 9],
       [2, 1],
       [8, 2],
       [5, 9],
       [7, 9],
       [2, 0]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr = np.random.random((3, 5))
arr

array([[0.9573412 , 0.45787744, 0.9058134 , 0.57519329, 0.3597125 ],
       [0.48804803, 0.24828577, 0.83234817, 0.61604703, 0.62165621],
       [0.86774928, 0.04484593, 0.44208642, 0.11982299, 0.46114167]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = np.random.randint(0, 10, size=(4, 6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = np.random.randint(1, 10, size=(3, 7))
display(arr)

# Find the unique numbers in the array you just created
np.unique(arr)

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
zero_array = arr[0]
zero_array

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
arr[2]

array([4, 9, 2, 9, 5, 2, 4])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2, :2]

array([[9, 1],
       [5, 3]])

In [23]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))
display(arr, ones)

array([[9, 6, 9, 8, 6],
       [8, 7, 1, 0, 6],
       [6, 7, 4, 2, 7]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Add the two arrays together
display(arr = np.add(arr, ones))

In [25]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Try add the array of ones and the other most recent array together
display(np.add(ones, arr))

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [27]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
# Subtract the new array of ones from the other most recent array
arr = np.subtract(arr, ones)
arr

array([[ 8.,  5.,  8.,  7.,  5.],
       [ 7.,  6.,  0., -1.,  5.],
       [ 5.,  6.,  3.,  1.,  6.]])

In [31]:
# Multiply the ones array with the latest array
multi_arr = np.multiply(arr, ones)
display(multi_arr)

array([[ 8.,  5.,  8.,  7.,  5.],
       [ 7.,  6.,  0., -1.,  5.],
       [ 5.,  6.,  3.,  1.,  6.]])

In [32]:
# Take the latest array to the power of 2 using '**'
display(arr ** multi_arr)

array([[ 1.6777216e+07,  3.1250000e+03,  1.6777216e+07,  8.2354300e+05,
         3.1250000e+03],
       [ 8.2354300e+05,  4.6656000e+04,  1.0000000e+00, -1.0000000e+00,
         3.1250000e+03],
       [ 3.1250000e+03,  4.6656000e+04,  2.7000000e+01,  1.0000000e+00,
         4.6656000e+04]])

In [33]:
# Do the same thing with np.square()
display(np.square(multi_arr))

array([[64., 25., 64., 49., 25.],
       [49., 36.,  0.,  1., 25.],
       [25., 36.,  9.,  1., 36.]])

In [34]:
# Find the mean of the latest array using np.mean()
display(np.mean(arr))

4.733333333333333

In [35]:
# Find the maximum of the latest array using np.max()
display(np.max(arr))

8.0

In [36]:
# Find the minimum of the latest array using np.min()
display(np.min(arr))

-1.0

In [37]:
# Find the standard deviation of the latest array
display(np.std(arr))

2.6948510575210314

In [38]:
# Find the variance of the latest array
display(np.var(arr))

7.2622222222222215

In [42]:
# Reshape the latest array to (3, 5, 1)
arr = np.reshape(arr, (3, 5, 1))
arr

array([[[ 8.],
        [ 5.],
        [ 8.],
        [ 7.],
        [ 5.]],

       [[ 7.],
        [ 6.],
        [ 0.],
        [-1.],
        [ 5.]],

       [[ 5.],
        [ 6.],
        [ 3.],
        [ 1.],
        [ 6.]]])

In [43]:
# Transpose the latest array
arr.T

array([[[ 8.,  7.,  5.],
        [ 5.,  6.,  6.],
        [ 8.,  0.,  3.],
        [ 7., -1.,  1.],
        [ 5.,  5.,  6.]]])

What does the transpose do?

In [44]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr = np.random.randint(0, 10, (3, 3))
arr_2 = np.random.randint(0, 10, (3, 2))

In [45]:
# Perform a dot product on the two newest arrays you created
np.dot(arr, arr_2)

array([[ 46,  48],
       [ 62,  52],
       [113,  54]])

In [47]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr = np.random.randint(0, 10, (4, 3))
arr2 = np.random.randint(0, 10, (4, 3))

In [48]:
# Perform a dot product on the two newest arrays you created
np.dot(arr, arr2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [49]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr, arr2.T)

array([[127,  73,  51,  67],
       [ 79,  34,  69,  28],
       [117,  80,  84,  58],
       [ 73,   6,  45,  20]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [50]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr = np.random.randint(0, 10, (4, 3))
arr2 = np.random.randint(0, 10, (4, 3))

In [51]:
# Compare the two arrays with '>'
arr > arr2

array([[False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [52]:
# Compare the two arrays with '>='
arr >= arr2

array([[ True,  True, False],
       [ True, False, False],
       [False, False, False],
       [False,  True, False]])

In [53]:
# Find which elements of the first array are greater than 7
arr > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [54]:
# Which parts of each array are equal? (try using '==')
arr == arr2

array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [55]:
# Sort one of the arrays you just created in ascending order
np.sort(arr)

array([[0, 0, 4],
       [0, 0, 7],
       [1, 1, 5],
       [0, 4, 6]])

In [56]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr)

array([[0, 2, 1],
       [1, 2, 0],
       [0, 1, 2],
       [2, 1, 0]])

In [57]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr)

3

In [58]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr)

0

In [59]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr, axis=1)

array([1, 0, 2, 0])

In [60]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr, axis=0)

array([0, 1, 0])

In [62]:
# Create an array of normally distributed random numbers
np.random.normal(0, 1, (4, 3))

array([[ 1.40279431, -1.40185106,  0.58685709],
       [ 2.19045563, -0.99053633, -0.56629773],
       [ 0.09965137, -0.50347565, -1.55066343],
       [ 0.06856297, -1.06230371,  0.47359243]])

In [63]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.random.randint(1, 100, 10)

array([33, 40, 39, 82,  1, 11, 92, 57, 89, 50])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.