In [1]:
import numpy as np

Create a NumPy array with values ranging from 0 to 9.

In [4]:
a = np.array(range(0, 9))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Reshape a 1D NumPy array into a 2D array with 3 rows and 3 columns.

In [5]:
a = a.reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Generate a random NumPy array of size 3x3 with values between 0 and 1.


In [10]:
random_a = np.random.randint(0, 2, (3, 3))
random_a

array([[1, 1, 0],
       [1, 0, 1],
       [1, 0, 0]])

Perform element-wise multiplication between two NumPy arrays of the same shape.


In [12]:
res = random_a * a
res

array([[0, 1, 0],
       [3, 0, 5],
       [6, 0, 0]])

Compute the mean, median, and standard deviation of a NumPy array.


In [14]:
print(f"Mean: {np.mean(res)}")
print(f"Median: {np.median(res)}")
print(f"Std: {np.std(res)}")


Mean: 1.6666666666666667
Median: 0.0
Std: 2.260776661041756


Find the index of the maximum value in a NumPy array.


In [20]:
i_max = np.argmax(res,)
i_max

6

Create a diagonal matrix from a given 1D NumPy array.


In [22]:
diag_mtx = np.diag(np.array(range(0,3)))
diag_mtx

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

Concatenate two NumPy arrays vertically and horizontally.


In [27]:
print(f"Axis = 0: {np.concatenate((a, random_a), axis=0)}")
print(f"Axis = 1: {np.concatenate((a, random_a), axis=1)}")

Axis = 0: [[0 1 2]
 [3 4 5]
 [6 7 8]
 [1 1 0]
 [1 0 1]
 [1 0 0]]
Axis = 1: [[0 1 2 1 1 0]
 [3 4 5 1 0 1]
 [6 7 8 1 0 0]]


Convert a NumPy array into a Python list.


In [30]:
a_list = a.tolist()
a_list

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

Calculate the dot product of two NumPy arrays.

In [28]:
print(f"Dot prod: {np.dot(a, random_a)}")

Dot prod: [[ 3  0  1]
 [12  3  4]
 [21  6  7]]
